name:                iamcheck
version:             0.1.0.0
github:              "github.com/nodebee/iamcheck"
license:             MIT
author:              "Laszlo Klock"
maintainer:          "laszlo@nodebee.io"
copyright:           "2021 Laszlo Klock"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nodebee/iamcheck#readme>

dependencies:
- base >= 4.14 && < 5
- sbv
- aeson
- text
- bytestring
- vector
- unordered-containers
- lens
- mtl
- transformers
- some
- dependent-sum-template
- scientific
- optparse-applicative
- file-embed
- containers

library:
  source-dirs: src

executables:
  iamcheck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iamcheck

tests:
  iamcheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iamcheck
    - HUnit
