name: Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: install z3
        run: sudo apt-get install -y z3

      - name: Cache dependencies 
        uses: actions/cache@v2
        env:
          cache-name: stack
        with:
          path: ~/.stack
          key: ${{ env.cache-name }}-${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}

      - name: Build
        run: stack build --ghc-options="-Wall -Werror"

      - name: Run tests
        run: stack test --ghc-options="-Wall -Werror"

      - name: Package
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/iamcheck-exe
          cp "$dir/iamcheck-exe" package/iamcheck
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iamcheck-exe
          path: package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest-linux-x64
          files: package/iamcheck
