name: Tests
on: 
  pull_request:
    paths-ignore:
      - '**.md'
  push:
   paths-ignore:
     - '**.md'
   branches:
     - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: install z3
        run: sudo apt-get install -y z3

      - name: Cache dependencies 
        uses: actions/cache@v2
        env:
          cache-name: stack
        with:
          path: ~/.stack
          key: ${{ env.cache-name }}-${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}

      - name: Build
        run: stack build --ghc-options="-Wall -Werror"

      - name: run tests
        run: stack test --ghc-options="-Wall -Werror"


